// ======================================================================
// Base Processor/Visitor class, auto-generated							
// 	Do NOT edit this file												
// 	Aditional methods should be defined in another file					
// ======================================================================
using System;
using System.Collections.Generic;
using System.Text;
using crosspascal.ast.nodes;

namespace crosspascal.ast
{
	public abstract partial class Processor
	{
		//	Complete interface to be implemented by any specific AST processor	
		
	}
}
