// ---------------------------------------------------------------------
// Base Processor class, auto-generated									
// 	Do NOT edit this file												
// 	Additional methods should be defined in another file				
// ---------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using crosspascal.ast.nodes;

namespace crosspascal.ast
{
	public abstract partial class Processor
	{
	}
}
